# Generated by Django 4.0.1 on 2022-01-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_in_priimek', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClanekVsebina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besedilo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Revija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revija', models.IntegerField(choices=[(0, 'Glasbena Mladina'), (1, 'Muska'), (2, 'Glasna')], default=0)),
                ('datum_izdaje', models.DateField()),
                ('stevilka', models.IntegerField()),
                ('pdf', models.FileField(upload_to='revije/pdf')),
                ('txt', models.FileField(upload_to='revije/txt')),
            ],
        ),
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('podnaslov', models.CharField(blank=True, max_length=255, null=True)),
                ('stran_v_reviji', models.IntegerField()),
                ('stran_v_pdf_dokumentu', models.IntegerField()),
                ('kategorija', models.IntegerField(choices=[(0, 'Članek'), (1, 'Interviju')])),
                ('avtorji', models.ManyToManyField(blank=True, to='revije.Avtor')),
                ('revija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revije.revija')),
                ('vsebina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='revije.clanekvsebina')),
            ],
        ),
    ]
