# Generated by Django 4.0.1 on 2022-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='kategorija',
            field=models.IntegerField(choices=[(0, 'Članek'), (1, 'Interviju')], default=0),
        ),
    ]
