# Generated by Django 3.1.7 on 2022-01-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0002_alter_clanek_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='vsebina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revije.clanekvsebina'),
        ),
        migrations.AlterField(
            model_name='clanekvsebina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revija',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
