# Generated by Django 3.1.7 on 2022-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0003_auto_20220125_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revija',
            name='pdf',
            field=models.FileField(blank=True, upload_to='revije/pdf'),
        ),
        migrations.AlterField(
            model_name='revija',
            name='txt',
            field=models.FileField(blank=True, upload_to='revije/txt'),
        ),
    ]
