# Generated by Django 3.1.7 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0004_auto_20220125_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='revija',
            name='html',
            field=models.FileField(blank=True, upload_to='revije/html'),
        ),
    ]
