# Generated by Django 3.1.7 on 2022-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0005_revija_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='revija',
            name='from_fn',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
