# Generated by Django 3.1.7 on 2022-02-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0006_revija_from_fn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revija',
            name='stevilka',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
