# Generated by Django 3.1.7 on 2022-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0007_auto_20220203_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='kategorija',
            field=models.IntegerField(choices=[(0, 'Članek'), (1, 'Intervju')], default=0),
        ),
    ]
