# Generated by Django 3.1.7 on 2022-02-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0008_auto_20220203_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtor',
            options={'verbose_name': 'Avtor', 'verbose_name_plural': 'Avtorji'},
        ),
        migrations.AlterModelOptions(
            name='clanek',
            options={'verbose_name': 'Članek', 'verbose_name_plural': 'Članki'},
        ),
        migrations.AlterModelOptions(
            name='clanekvsebina',
            options={'verbose_name': 'Vsebina članka', 'verbose_name_plural': 'Vsebine člankov'},
        ),
        migrations.AlterModelOptions(
            name='revija',
            options={'verbose_name': 'Revija', 'verbose_name_plural': 'Revije'},
        ),
        migrations.AlterField(
            model_name='revija',
            name='html',
            field=models.FileField(blank=True, upload_to='revije/html', verbose_name='HTML datoteka'),
        ),
        migrations.AlterField(
            model_name='revija',
            name='pdf',
            field=models.FileField(blank=True, upload_to='revije/pdf', verbose_name='PDF datoteka'),
        ),
        migrations.AlterField(
            model_name='revija',
            name='stevilka',
            field=models.IntegerField(blank=True, null=True, verbose_name='Številka'),
        ),
        migrations.AlterField(
            model_name='revija',
            name='txt',
            field=models.FileField(blank=True, upload_to='revije/txt', verbose_name='TXT datoteka'),
        ),
    ]
