# Generated by Django 3.1.7 on 2022-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0009_auto_20220204_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='revija',
            name='zakljuceno',
            field=models.BooleanField(default=False, verbose_name='Zaključeno'),
        ),
    ]
