# Generated by Django 3.1.7 on 2022-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0010_revija_zakljuceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='vsebina',
            field=models.TextField(blank=True, null=True),
        ),
    ]
