# Generated by Django 3.1.7 on 2022-02-08 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0011_auto_20220208_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='revija',
            name='letnik',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
