# Generated by Django 3.1.7 on 2022-02-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0012_revija_letnik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClanekVsebina',
        ),
    ]
