# Generated by Django 3.1.7 on 2022-02-10 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revije', '0013_delete_clanekvsebina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revija',
            name='letnik',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
